In [77]:

##importation de Numpy
import numpy as np

In [45]:
 ##créer un tableau numpy qui contient les éléments suivants:1,5,7,8.
np.array([1,5,7,8])

array([1, 5, 7, 8])

In [78]:
##créer un tableau numpy qui contient les éléments suivants:1,2,3,4,5,6,7,8,9

np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:

##Créer un tableau de 10 éléments rempli de 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:

##Créer un tableau de 2 lignes 5 colonnes rempli de 0
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:

##Créer un tableau de 10 éléments rempli de 1

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [82]:

##Créer un tableau de 2 lignes 5 colonnes rempli de 1
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:

##Créer un tableau de 10 éléments rempli de 8.5
np.full(10,8.5)

array([8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5])

In [84]:

##Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
##Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs
##allant de 1 à 9 inclus
tab=np.arange(1,10)
tableau= tab.reshape(3,3)
tableau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:


##Créer une matrice identité  de 4 lignes 4 colonnes
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:

##Tableau rempli de valeurs aléatoires normales centrées en zéro
np.random.randn(5)

array([0.23074729, 0.93397849, 1.82111631, 0.90813586, 0.04752355])

In [88]:

##Créer un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et 10

np.random.randint(1,11
,20)

array([ 1,  7,  9,  4,  9,  9, 10,  2,  7,  6,  5,  2,  5,  4,  1,  5,  6,
        4,  5,  2])

In [89]:


##Transformer le tableau précédent en matrice de 4 lignes 5 colonnes
Tab = np.random.randint(1,11
,20)
TranformTab = Tab.reshape(4,5)
TranformTab

array([[ 5,  8,  8, 10,  4],
       [ 5,  2,  2,  5,  3],
       [ 4,  8,  5,  5,  8],
       [ 1,  3,  3,  8,  7]])

In [90]:

##créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude egale
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Exo2

In [91]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:

##Afficher le nombre de lignes et de colonnes
a.shape

(3, 3)

In [59]:

##Afficher la dimension de mon tableau
a.ndim

2

In [60]:

##Afficher le nombre d'élément de mon tableau
a.size

9

In [61]:


##Afficher le type des éléments du tableau
a.dtype

dtype('int64')

Exo3

In [93]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
##afficher la valeur 5 qui est dans le tableau
a[1][1]

5

In [95]:

##remplacer le 5 qui est dans le tableau par 0
a[1][1]=0
a

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [96]:

##afficher les chiffres 3,6,9 du tableau
a[0:,2]

array([3, 6, 9])

In [97]:
##créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiers aléatoires compris entre 0 et 9
Tab = np.random.randint(0,10
,12)
Tab.reshape(4,3)

array([[1, 7, 3],
       [5, 7, 2],
       [7, 0, 5],
       [1, 5, 6]])

In [98]:

##vérifier qu'il y a des nombres inférieur à 5
np.any(Tab<5)

True

In [99]:

##remplacer les nombres inférieur à 5 par 0
Tab[Tab<5]=0
Tab

array([0, 7, 0, 5, 7, 0, 7, 0, 5, 0, 5, 6])

Exo4

In [100]:


##.Créer un tableau de 4 lignes et 3 colonnes rempli de 11 nombres entiers aléatoires compris entre 0 et 9
Tab = np.random.randint(0,10
,(4,3))
Tab

array([[8, 3, 8],
       [9, 6, 9],
       [6, 7, 3],
       [7, 1, 7]])

In [101]:

##le type des éléments du tableau
Tab.dtype

dtype('int64')

In [70]:


## changer le type des éléments du tableau en float32
Tab=np.float32(Tab)
Tab

array([[8., 2., 3.],
       [4., 1., 5.],
       [8., 1., 3.],
       [0., 8., 0.]], dtype=float32)

In [102]:

## ajouter 3 à la fin du tableau à une dimension
Tab=np.append(Tab,3)
Tab

array([8, 3, 8, 9, 6, 9, 6, 7, 3, 7, 1, 7, 3])

In [103]:

##Transformer le tableau en matrice dénommée “a” de 3 lignes et  4colonnes
a= Tab
a=np.delete(a,-1)
a=a.reshape(3,4)
a

array([[8, 3, 8, 9],
       [6, 9, 6, 7],
       [3, 7, 1, 7]])

In [104]:

## Créer une matrice dénommée“b” de 3 lignes et 4 colonnes remplie de série d'entiers successifs allant de 1 à 12 inclus
b= np.arange(1,13)
b=b.reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:

## Créer une matrice dénommée“c” qui est la concaténation des deux tableaux “a” et“b” dans le sens horizontale
c= np.hstack((a,b))
c

array([[ 8,  3,  8,  9,  1,  2,  3,  4],
       [ 6,  9,  6,  7,  5,  6,  7,  8],
       [ 3,  7,  1,  7,  9, 10, 11, 12]])

In [107]:

## Créer une matrice dénommée“d” qui est la concaténation des deux tableaux “a” et“b” dans le sens verticale
d=  np.vstack((a,b))
d

array([[ 8,  3,  8,  9],
       [ 6,  9,  6,  7],
       [ 3,  7,  1,  7],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:

##aplatir le tableau d
d= np.ravel(d)
d

array([ 8,  3,  8,  9,  6,  9,  6,  7,  3,  7,  1,  7,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12])

In [110]:

##supprimer le dernier élément dans le tableau d
d=np.delete(d,-1)
d

array([ 8,  3,  8,  9,  6,  9,  6,  7,  3,  7,  1,  7,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11])

Exo5

In [ ]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:

##faire la somme des éléments du tableau
a.sum()

74

In [112]:

##faire la somme des éléments du tableau par colonnes
a.sum(axis=0)

array([17, 19, 15, 23])

In [113]:

##faire la somme des éléments du tableau par ligne
a.sum(axis=1)

array([28, 28, 18])

In [115]:

##faire le des éléments du tableau par colonnes
Z = np.prod(a,axis=0)
Z

array([144, 189,  48, 441])

In [116]:

##Afficher le minimum
a.min()

1

In [118]:

##afficher le maximum
a.max()

9

In [119]:

##afficher la moyenne
a.mean()

6.166666666666667

In [120]:

##afficher la variance
a.var()

5.972222222222221

In [121]:

##afficher l'écart type
a.std()

2.4438130497691963